
<?php echo $this->getContent() ?>

<ol class="breadcrumb">
    <li><?php echo $this->tag->linkTo(array("$plural$/new", "Create $plural$")) ?></li>
</ol>

<?php echo $this->tag->form(array("$plural$/search", "autocomplete" => "off")) ?>

    <h1>Search $plural$</h1>
$captureFields$
    <div class="btn-toolbar" role="toolbar">
        <div class="btn-group">
            <button type="submit" class="btn btn-default">Search</button>
        </div>
    </div>
</form>
