
<?php echo $this->getContent(); ?>

<ol class="breadcrumb">
    <li><?php echo $this->tag->linkTo(array("$plural$", "Back")) ?></li>
</ol>

<?php echo $this->tag->form("$plural$/create") ?>

    <h1>Create $plural$</h1>
$captureFields$
    <div class="btn-toolbar" role="toolbar">
        <div class="btn-group">
            <button type="submit" class="btn btn-default">Search</button>
        </div>
    </div>
</form>
