<?php use Phalcon\Tag; ?>

<?php echo $this->getContent(); ?>

<ol class="breadcrumb">
    <li><?php echo $this->tag->linkTo(array("$plural$", "Back")) ?></li>
    <li><?php echo $this->tag->linkTo(array("$plural$/new", "Create ")); ?></li>
</ol>

<h1>$plural$</h1>

<table class="table">
    <thead>
        <tr>
$headerColumns$         </tr>
    </thead>
    <tbody>
    <?php foreach ($page->items as $singularVar$) { ?>
        <tr>
$rowColumns$            <td><?php echo $this->tag->linkTo(array("$plural$/edit/" . $singularVar$->$pk$, "Edit")); ?></td>
            <td><?php echo $this->tag->linkTo(array("$plural$/delete/" . $singularVar$->$pk$, "Delete")); ?></td>
        </tr>
    <?php } ?>
    </tbody>
</table>

<ul class="pager">
    <li><?php echo $this->tag->linkTo("$plural$/search", "First") ?></li>
    <li><?php echo $this->tag->linkTo("$plural$/search?page=" . $page->before, "Previous") ?></li>
    <li><?php echo $this->tag->linkTo("$plural$/search?page=" . $page->next, "Next") ?></li>
    <li><?php echo $this->tag->linkTo("$plural$/search?page=" . $page->last, "Last") ?></li>
    <li><?php echo $page->current, "/", $page->total_pages ?></li>
</ul>

